version: '3'
services:
    nginx:
      build: ./infra/nginx
      ports:
        - 8090:80
      volumes:
        # ホストのdefault.confを同期
        - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        # htmlとホストのhtmlを同期
        # - ./infra/www/html:/var/www/html

    php:
      build: ./infra/php
      volumes:
    #   # htmlとホストのhtmlを同期
          - ./www/html:/var/www/html

    db:
      build: ./infra/mysql
      ports:
        - 13306:3306
    #     # ホストのmysqlとdataを同期
      volumes:
        - ./mysql/mysql:/var/lib/mysql
      environment:
        # 必要なパス
        MYSQL_ROOT_PASSWORD: secret

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest
    #     ports:
    #         - 8888:80
    #     depends_on:
    #         - db




#  depends_onは依存関係
# 指定されたサービスの起動より後に起動する
# - ./docker/nginx/nginx.conf
# - .:/var/www/html？？
# - ./docker:/var/www/html
# - ./docker/mysql/data

# ↓なんでこの関係性？

# - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
# - ./www/html:/var/www/html
# - ./www/html:/var/www/html
# - ./mysql/data:/var/lib/mysq


# MySQLにおけるスーパーユーザである
# rootアカウントに設定するためのパスワードを指定します。
# https://php-archive.net/php/docker-php-environment/2/